- opensnitch/connection.py
- opensnitch/proc.py
- setup.py
The way to get the PID of the process that created a connection has been improved using psutils (similar to *nix lsof tool)
> Improved connection parsing

- opensnitch/rule.py
Implements rules persistence using a sqlite database.
I don't know if you want to save all decisions (allow/deny once/all).
> Implements rules persistence

- bin/opensnitch
Fixes running on systems where python is not in /usr/bin (such as in the case of virtualenvs, nixos) or when /usr/bin/python is python3
> Explicitly set shebang to python2 via /usr/bin/env

- opensnitch/connection.py
- opensnitch/dns.py
- opensnitch/rule.py
- opensnitch/snitch.py
- opensnitch/ui.py
There are a few non-obvious reasons why this commit is so big:
The PyQt mainloop must run in main thread.. This was not particularly
easy since the packet callbacks were running in the main thread.
Because of the PyQt running in the main thread thing NetFilterQueue had
to be wrapped up in a thread.
The packet callback is now dispatched to a thread if user has to be
prompted.
Packets are sent over a queue to the ui thread.
SQLite connection must be called from the same thread it was created
in. Thats why all the calls are wrapped up in a lock and create a new
connection. This is not ideal but I would say it's good enough for now.
> Fix packet blocking behaviour while UI is open (fixes #40)

- opensnitch/snitch.py
- opensnitch/ui.py
Currently the UI will show dialog if the connection got a permanent rule
after the connection was queued.
This fixes this behaviour.
We are also having an issue where the QComboBox won't get reset to Once
after being set.
> Dont show dialog if connection got permanent rule

- opensnitch/__main__.py
- opensnitch/iptables.py
- opensnitch/snitch.py
- setup.py
Reviving my PR https://github.com/evilsocket/opensnitch/pull/41 and
polishing it up a bit for easier usage.
The wrapper script makes running without root as easy as `sudo opensnitch` and that will check  the SUDO_USER environment variable by default or the argument `--user`
Why this is needed:
I was working on getting D-bus based IPC working and wanted to do my dev work using the D-Bus Session Bus (the one running in my desktop session).
Running something in my users session bus is very tricky from the root account and not something I feel comfortable expecting from users even at this point.
Using the System Bus is also out of the question for now since it needs to be provided by a .service file on systemd based distros (which is great for us since it solves the issue of some malware …
> Use iptables trough iptc, enables rootless operation

- ui/setup.py
fix install error of package_data
TypeError: Can't convert 'list' object to str implicitly
> Bug fix - TypeError list str

- README.md
Installation requires python3-pip and pip installed grpcio-tools to complete successfully.
Signed-off-by: Peter Ansell <p_ansell@yahoo.com>
> Fix #140 : Include python3-pip and grpcio-tools in readme

- daemon/conman/connection.go
- daemon/dns/track.go
- daemon/firewall/rules.go
- daemon/procmon/watcher.go
- ui/opensnitch/dialogs/stats.py
This is to address #184: https://github.com/evilsocket/opensnitch/issues/184
`sys_execve` does not appear to be an available filter function:
```
audit_log_execve_info
do_execveat_common.isra.37
__ia32_compat_sys_execve
__ia32_compat_sys_execveat
__ia32_sys_execve
__ia32_sys_execveat
__x64_sys_execve
__x64_sys_execveat
do_execve
do_execveat
```
In order to fix this, I tried `__x64_sys_execve` and `do_execve`.  Both appear to allow the daemon to proceed with initialization and to properly operate the packet filter.  The UI connects to the daemon and pops up windows upon alerts with no issue.
> Update probed function sys_execve to do_execve

- ui/opensnitch_ui.desktop
The desktop entry currently lists support for at least one mime type, but does not provide codes like `%f`, `%F`, `%u` or `%U` for the `Exec` key.
If the application can indeed handle files of the listed mime type, it should specify a way to pass the filenames as parameters, or it should not specify the `MimeType` key to begin with.
> ui/opensnitch_ui.desktop: Drop MimeType declaration

- ui/bin/opensnitch-ui
This fixes the scaling issue on hi dpi displays (4K, etc) that render the window too small with overlapping widgets.
> Add UI Scaling for HiDPi Support

- ui/opensnitch/dialogs/stats.py
In stats.py, line 205 there is an error:
pw_name = pwd.getpwall(int(uid)).pw_name
the function getpwall of pwd returns all the password entries and not accept arguments, must be getpwuid
> Fix function to get username from uid.

- ui/opensnitch/dialogs/stats.py
This patch is to fix a problem where the UI would crash out whenever a dialog was responded to, first complaining that pw_name wasn't initialised, then that pwd.getpwall() doesn't normally take arguments. See #197 for more information.
> Fixes issue #197 - modified user stats to use pwd.getpwuid 

- daemon/conman/connection.go
- daemon/netstat/entry.go
- daemon/netstat/find.go
- daemon/netstat/parse.go
Fixes a crash caused by trying to parse too large hexadecimal numbers into signed ints. Parses to uint instead.
For issue #228
> Fixes #228: Parse IP and port to uint

- ui/opensnitch/service.py
This was failing because the 2 format arguments are being applied with higher precedence than the string concatenation, and the string that the formatting is being applied to only takes 1 argument
> Add () to str cat to fix % fmt

- daemon/netstat/find.go
This change should fix #206 (Java applications are not noticed by OpenSnitch). It was made possible thanks to the IPv6 support provided by @jkozera.
Some applications (especially Java-based) use the AF_INET6 socket for IPv4 communication. Those connections were previously not detected. With this patch it might work better.
You can test this as follows:
1. Install OpenJDK `sudo apt install openjdk-11-jdk-headless`
2. Open the Java REPL by executing `$ jshell`
3. Inside JShell enter following Java code which makes a HTTP Request to github.com:
4. `((HttpURLConnection) new URL("https://github.com").openConnection()).getResponseCode()`
Without this patch the connection to github.com goes through without prompting, with the patch applied OpenSnitch can catch it.
Leave jshell with `/exit`.
> Also detect applications that use the AF_INET6 socket for IPv4 connections (like Java)

- ui/opensnitch/dialogs/prompt.py
Hi there,
this should resolve #252 by adding an additional dot in front of the selected domain.
So that the created regex looks like `.*\.apple\.com` instead of `.*apple\.com`
> UI: improve regex for domain matching

- ui/opensnitch/res/stats.ui
Right now because this button always has a focus if the user accidentally presses Enter even while typing in the Filter field, all db will be cleaned.
> Disable always-on focus on cmdCleanSql button.

- daemon/statistics/event.go
- daemon/statistics/stats.go
- proto/Makefile
- proto/ui.proto
- ui/opensnitch/service.py
- Use daemon's event timestamp in UI.
- Use the timestamp instead of the event object when iterating over the last events. ~15x speed increase.
- Increase event buffer to 100. On my machine I routinely hit the ceiling of 50 events under some multitasking workloads which results in new connections not being logged.
> Use daemon's event timestamp in UI.

- daemon/main.go
Mullvad VPN uses an nfmark on packets when (re-)establishing a connection with their VPN servers.
If we don't preserve the nfmark, the connection will never be (re-)established.
> preserve nfmark when NF_ACCEPT'ing packets

- daemon/main.go
This should solve https://github.com/gustavo-iniguez-goya/opensnitch/issues/82
Without this patch passing -debug on command line has no effect because
`ui.NewClient ` reads the config and sets a logfile.
We explicitely set `logFileToUse = log.StdoutFile` and restore the expected behaviour.
> fix logging when flag is passed on command line

- daemon/main.go
- daemon/ui/client.go
I tested this by running a script which generated 100 new connections per second and setting the UI popup timeout to 0 with default action deny. The script ran for at least 24h.
The binary was built with -race for race detection.
> do not block connection processing when GUI popup is active.

- daemon/go.mod
- proto/Makefile
- proto/ui.proto
When building the project with protoc-gen-go version 1.5.1,
it fails with the following:
```
protoc -I. ui.proto --go_out=plugins=grpc:../daemon/ui/protocol/
protoc-gen-go: unable to determine Go import path for "ui.proto"
Please specify either:
• a "go_package" option in the .proto source file, or
• a "M" argument on the command line.
See https://developers.google.com/protocol-buffers/docs/reference/go-generated#package for more information.
--go_out: protoc-gen-go: Plugin failed with status code 1.
```
This can be fixed by adding the full go package as an option in the
proto file. To make sure the code is generated to the correct path,
we also have to add add the `paths=source_relative` option to the
protoc plugin.
After this, the code is generated correctly, but the generated code …
> Support more recent protoc-gen-go

- ui/requirements.txt
My OS comes with grpcio-tools 1.36.1, which seems to work fine, so it
would be nice to allow the ui to use that instead of building 1.10.1
specifically for opensnitch.
> Allow using newer grpcio-tools

- daemon/procmon/details.go
- daemon/procmon/parse.go
- daemon/procmon/process.go
- ebpf_prog/opensnitch.c
Some connections are initiated from kernel space, like WireGuard VPNs (#454), NFS or SMB connections (#502) and ip tunnels (#500).
More information regarding this change: #493
TODO:
- support for i386: there's an invalid access reading udp header.
- test it on arm*.
> Allow to intercept more kernel connections

- ui/opensnitch/dialogs/prompt.py
Set prompt width and height after initial display; set prompt minimum and maximum size using initial width and height values
> Prompt UI height and width fixes

- wiki/Home.md
> add Repology banner to wiki home

- README.md
This banner can help people find their corresponding distro packages.
> add Repology badge to README

- daemon/opensnitchd.service
- debian/opensnitch.service
It was a full sentence that looked out of place. Official documentation
of systemd recommends to make it a short capitalized label, preferably a
noun.
See [man page `systemd.unit`](https://www.freedesktop.org/software/systemd/man/systemd.unit.html#Description=).
> Improve systemd service unit name

- ui/i18n/locales/de_DE/opensnitch-de_DE.ts
- ui/i18n/locales/es_ES/opensnitch-es_ES.ts
- ui/i18n/locales/eu_ES/opensnitch-eu_ES.ts
- ui/i18n/locales/fr_FR/opensnitch-fr_FR.ts
- ui/i18n/locales/hu_HU/opensnitch-hu_HU.ts
- ui/i18n/locales/ja_JP/opensnitch-ja_JP.ts
- ui/i18n/locales/pt_BR/opensnitch-pt_BR.ts
- ui/i18n/locales/ro_RO/opensnitch-ro_RO.ts
- ui/opensnitch/res/preferences.ui
This PR fixes the following typo:
`Disable pop-ups, only display an notification` to `Disable pop-ups, only display a notification`
> Fix a minor typo

- daemon/dns/ebpfhook.go
- daemon/main.go
- ebpf_prog/Makefile
- ebpf_prog/opensnitch-dns.c
Thanks for the great software. I recently rediscovered opensnitch and I am very happy with it.
For a while now I have been using systemd-resolved combined with DNS over TLS (DoT).
When using DoT or DoH opensnitch cannot intercept the dns packets. Therfore the UI always shows IP addresses instead of hostnames.
To fix this issue I created a watch on the systemd-resolved debug logs. The hostnames are parsed from this log file.
It is definitly not the most elegant solution to this problem, but it worked for me.
The debug log must be enabled manually using the following command. `sudo resolvectl log-level debug`
I would be very happy for feedback or alternative solutions to the problem.
Probably this functionality should be optional because it might use more resources and it adds a delay …
> Add systemd-resoved listener

- daemon/netfilter/queue.go
- daemon/netfilter/queue.h
Currently `queue.go` and `queue.h` use nonstandard type definitions which are unsupported by the musl libc implementation. This PR changes the definitions to be standard and allows the project to compile on musl.
> Allow building on systems using musl

- wiki/Installation.md
Hey all,
Awesome application and glad to see it grow and improve over the years. I recently was making the upgrade from 1.3.x version to 1.5.0 and I noticed the latest application installs python packages using `apt` which is a wonderful add and makes me more comfortable with the installation process.
One thing I noticed running `sudo pip list` and `sudo pip show` is that the python package that will be used will still be the ones that were installed prior using `sudo pip` in `/usr/local/lib/` rather than the `apt` installed ones which land in `/usr/lib/`. I _think_ it would be better for users running older versions to actually `pip uninstall` these dependencies before running `apt` using the newer `deb`.
In addition to that I think the list of packages to be uninstalled can be extended …
> `pip uninstall` that accounts transient dependencies

- daemon/dns/ebpfhook.go
On arch linux, and likely other distros, [libc.so](http://libc.so/).6 is shipped stripped by default. this means `.symtab` does not exist and `elffile.Symbols()` returns with "no symbol section" error resulting in dns uprobes being unable to be attached. This pr changes the call to `.DynamicSymbols()` to alleviate this problem. This ensures a broader range of distro compatibility.
```EBPF-DNS: Failed to find symbol for uprobe uretprobe/gethostbyname : no symbol section
EBPF-DNS: Failed to find symbol for uprobe uprobe/getaddrinfo : no symbol section
EBPF-DNS: Failed to find symbol for uprobe uretprobe/getaddrinfo : no symbol section
EBPF-DNS: Failed to find symbols for uprobes.
EBPF-DNS: Unable to attach ebpf listener.```
> Fixes attachment of dns uprobes when libc is stripped of symbol names

- daemon/firewall/nftables/exprs/enums.go
- daemon/firewall/nftables/exprs/protocol.go
- daemon/firewall/nftables/exprs/utils.go
- daemon/firewall/nftables/parser.go
- daemon/firewall/nftables/rule_helpers.go
- daemon/system-fw.json
- Add support for all available nftables ICMPv6 types (ip6tables -m icmpv6 --help)
- Build nftables ICMPv6 rules
- Create a default outbound ICMPv6 echo-request/reply rule
(currently outbound echo-request ICMPv6 is by default denied)
```
$ doas nft list table inet mangle
table inet mangle {
chain output {
type filter hook output priority mangle; policy accept;
icmp type { echo-reply, echo-request } accept
icmpv6 type { echo-request, echo-reply } accept
ct state related,new queue flags bypass to 0
}
[...]
```
> fw: support for icmpv6 nftables in system rules

- wiki/Compilation.md
There is no "lrelease" binary on Fedora, which is needed to build the UI properly. There is a "lrelease-qt5" binary, which is part of the package "qt5-linguist".
To fix the UI not building properly on Fedora, symlink /usr/lib64/qt5/bin/lrelease-qt5 to /usr/local/bin/lrelease:
```
sudo ln -s /usr/lib64/qt5/bin/lrelease-qt5 /usr/local/bin/lrelease
```
Then it should build properly.
> Add instructions on how to fix UI failing to build properly on Fedora

- daemon/system-fw.json
Changed 'tcp' to 'udp' to make wireguard rule ```Exclude WireGuard VPN from being intercepted``` work.
> sys firewall: fixed wrong wireguard protocol

- ui/i18n/locales/hu_HU/opensnitch-hu_HU.ts
Port translation was "kikötő" which means harbor and we need here "port" or "portszám" for port.
> Here port should be also port in hungarian language.

- daemon/Makefile
This is a handful of improvements to the daemon/Makefile that make it easier to package opensnitch on other distros. make's DESTDIR and PREFIX are widely used, and install is a very common way to handle installing/copying files/dirs to a location.
This *might* add some new dependency on `install` if some distro / environment doesn't include it, but it's a part of coreutils and busybox has a module for it... so it's likely everywhere already.
> daemon/Makefile: improvements to make distro packaging easier

- Makefile
- ui/Makefile
This allow builders to control which make program to use and let make take care of changing the working directory.
> Use '$(MAKE) -C dir' instead of 'cd dir && make' when building in subdirectory

- .github/workflows/go.yml
The eatmydata package block programs from using file system sync, a kernel operation slowing down execution to ensure data reaches the disk before continuing.  No-one care if the hard disk got any data for the continous integration tests if the machine crashes halfway through the test, so this is just wasted time.
> Speed up Go build by using eatmydata.

- debian/control
This will make it install by default, while still allowing the package to be installed without it.
> The GUI work better with python3-pyasn, added it as Recommends.

- utils/legacy/make_ads_rules.py
Upgrades chameleons url to https from http. Thus increasing security by a small amount
> Upgrade chameleons url to https

- debian/control
No need to repeat the package name, and make sure to mention the firewall is interactive.  Use the same phrase in both packages.
> Improve short debian package description.

- debian/control
This ensure 'apt install opensnitch' by default also install the graphical user interface.  Also let the python3-opensnitch-ui package suggest opensnitch, to let users know about the daemon package.  Not using recommends here to avoid circular recommend relation between the two packages.
> Added Debian package relation between opensnitch and python3-opensnitch-ui.

- ui/i18n/locales/de_DE/opensnitch-de_DE.ts
- ui/i18n/locales/es_ES/opensnitch-es_ES.ts
- ui/i18n/locales/fr_FR/opensnitch-fr_FR.ts
- ui/i18n/locales/hu_HU/opensnitch-hu_HU.ts
- ui/i18n/locales/ja_JP/opensnitch-ja_JP.ts
- ui/i18n/locales/lt_LT/opensnitch-lt_LT.ts
- ui/i18n/locales/nb_NO/opensnitch-nb_NO.ts
- ui/i18n/locales/pt_BR/opensnitch-pt_BR.ts
- ui/i18n/locales/ro_RO/opensnitch-ro_RO.ts
- ui/i18n/locales/ru_RU/opensnitch-ru_RU.ts
- ui/i18n/locales/tr_TR/opensnitch-tr_TR.ts
- ui/opensnitch/database/__init__.py
tooltips, by convention, look nicer without a terminal period; also, a typo was removed in some diagnostic text.
> fixed typo, made tooltip text more conventional

- daemon/opensnitchd-openrc
this PR adds a very basic script that would allow to get opensnitchd running under OpenRC init system. I've managed to get it to "work" i.e. not to crash, under Alpine 3.17 with Linux6.2.8-0-edge x86_64, but I keep getting this error:
```
Error creating queue #0: Error binding to queue: operation not permitted
```
I've set it to run using proc instead of bpf, because I have a hardened kernel. I can try giving it a test run in a VM without bpf hardening (I assume docker won't do in this case...). 
After this is merged and this issue resolved (I'll try to tackle this by myself, but any help is appreciated), I'd like to then proceed to package the application's components into an APKBUILD, so that it can be easily installed on Alpine.
> feat(daemon): add OpenRC script

- ui/opensnitch/notifications.py
This isn't an executable script so it shouldn't be needed.
> ui: remove unnecessary shebang

- ui/bin/opensnitch-ui
- ui/opensnitch/config.py
**Thanks to everyone involved with this project!** It's maturing well. Here's my attempt to contribute.
This change adds a new option to settings.conf: `server_max_message_length` (`DEFAULT_SERVER_MAX_MESSAGE_LENGTH`) accepting the following options:
- _4MiB_ (default)
- _8MiB_
- _16MiB_
The values are strings matched to set the corresponding integer for server `grpc.max_send_message_length` & `grpc.max_receive_message_length`. I'm guessing that few have encountered this problem based on reported issues. I don't think that exposing a GUI option is warranted nor is granular control.
The default of _4MiB_ can be increased within **~/.config/opensnitch/settings.conf** by adding the following to `[global]`:
`server_max_message_length=8MiB`
Archlinux Flatpak Steam _[Insurgency: …
> Add non-gui setting for gRPC server max_message_length.

- daemon/default-config.json
- daemon/log/log.go
- daemon/main.go
- daemon/ui/client.go
- daemon/ui/config.go
- ui/opensnitch/dialogs/preferences.py
- ui/opensnitch/res/preferences.ui
- ui/tests/dialogs/__init__.py
- ui/tests/dialogs/test_preferences.py
This request adds two new options to configure the daemon logging:
- **LogUTC**: toggles `time.Now().UTC()` vs `time.Now().local()`
- **LogMicro**: enable microsecond timestamp
Both options are exposed within the UI.
> Introduce 2 new daemon logging options: LogUTC & LogMicro.

- ebpf_prog/Makefile
The `arch` command is deprecated on modern systems, and indeed, many distros do not provide it (one of those being Arch Linux, ironically). Since `uname` is already used in the Makefile, prefer its `-m` flag equivalent instead.
> use `uname -m` instead of the `arch` command

- ui/bin/opensnitch-ui
- ui/opensnitch/dialogs/stats.py
- ui/opensnitch/service.py
- ui/opensnitch/utils/xdg.py
- ui/requirements.txt
- ui/resources/opensnitch_ui.desktop
I have summarized the various changes here:
- Use of pyxdg
- Extension of xdg.py (autostart)
- control autostart in tray
- check if os-ui is already running
See also https://github.com/evilsocket/opensnitch/issues/950
> xdg updates + autostart + lockfile

- ui/bin/opensnitch-ui
- ui/opensnitch/service.py
This PR adds `--background` command line argument that starts GUI in background even when tray not available and uses QLocalSocket and QLocalServer instead of lockfile (now it is possible to open window without starting new instance, using launcher in programs menu).
Please review this code, because I never used Qt.
This will fix issue #940.
> Allow starting in background when tray not available

- ebpf_prog/Makefile
Currently, when compiling the eBPF module, in the Makefile, the output of `clang` is directly piped to `llc`. This is bad, because in this case, should `clang` fail, `llc` still runs, but produces faulty `.o` files. `make` never picks up on it and doesn't abort compilation - a success is reported across the board (apart from the `clang` log).
This patch removes the file and explicitly writes (and later deletes) `clang`'s output to a `.partial` file. This is later used as the input of `llc`.
> Use temporary files instead of piping in ebpf Makefile

- ui/opensnitch/config.py
- ui/opensnitch/database/__init__.py
- ui/opensnitch/dialogs/preferences.py
- ui/opensnitch/res/preferences.ui
- ui/opensnitch/service.py
- ui/opensnitch/utils/__init__.py
- Add [Write-Ahead Logging](https://www.sqlite.org/wal.html) option for file mode database
- Disable by default
- Migrate journal_mode and related `PRAGMA` statement handling from _create_tables() to new functions: get_journal_mode()/set_journal_mode()
This yields a significant reduction of constant IO writes on my systems when db file mode is enabled. 
Note that `PRAGMA synchronous = NORMAL` doesn't appear to activate properly. This problem occurs on master branch builds as well. Manual inspection of the db shows that synchronous always = FULL unless manually set directly but this warrants additional discussion elsewhere.
> Introduce Sqlite WAL journal mode

- ui/opensnitch/dialogs/stats.py
Typo discovered during translation.
> Fixed typo in translatable string (Your are->You are).

- daemon/go.mod
There are 1 security vulnerabilities found in golang.org/x/sys v0.0.0-20211205182925-97ca703d548d
- [CVE-2022-29526](https://www.oscs1024.com/hd/CVE-2022-29526)
Upgrade golang.org/x/sys from v0.0.0-20211205182925-97ca703d548d to 0.1.0 for vulnerability fix
Ideally, no insecure libs should be used.
By using the [GitHub Actions](https://github.com/murphysecurity/actions) configurations provided by murphysec, we can conduct automatic code security checks in our CI pipeline.
[PR Specification](https://www.oscs1024.com/docs/pr-specification/) from OSCS
> fix(sec): upgrade golang.org/x/sys to 0.1.0

- ui/opensnitch/service.py
I assume that the main gui window was just displaying statistics.
Now you can configure rules, and do other various settings, the menu point "Statistics" doesn't seem appropriate anymore..
> Improve wording in Top menu

- daemon/core/system.go
This fixes a minor issue where the same line is displayed twice in `opensnitchd -check-requirements`:
```
Checking system requirements for kernel version 6.8.9-asahi
------------------------------------------------------------------------------
Checking => CONFIG_KPROBES=y
Checking => CONFIG_KPROBES_ON_FTRACE=y
- KPROBES not fully supported by this kernel.
Checking => CONFIG_KPROBES_ON_FTRACE=y
- KPROBES not fully supported by this kernel.
```
> Remove duplicate regex in system.go for -check-requirements

- ebpf_prog/Makefile
* `%.bc` are autoremoved: [these LLVM IR files are intermediate](https://www.gnu.org/software/make/manual/html_node/Chained-Rules.html)
* `%.o` are now produced by a wildcard search
* introduced `.SUFFIXES:` [for cleaning up the implicit rules](https://www.gnu.org/software/make/manual/html_node/Suffix-Rules.html)
* else Makefile would have generated `%.o` from its own database.
> ebpf_prog/Makefile: temp files are now handled by a pattern rule

- utils/scripts/ads/update_adlists.sh
AdGuard no longer maintains/supports that file type, and the link points to a 404 error page. After removing all the references, the user will still be able to update their local blocklists.
> remove lagacy cname_trackers.txt reference from update_adlists.sh

- ebpf_prog/Makefile
`LLVM_STRIP` appears only once in Makefile:
```shell
LLVM_STRIP ?= llvm-strip -g
```
> ebpf_prog/Makefile: removed useless `LLVM_STRIP`

- ebpf_prog/opensnitch.c
Seen while compile eBPF using `make CC=clang`.
```
opensnitch.c:330:6: warning: unused variable 'zero_key' [-Wunused-variable]
330 |         u32 zero_key = 0;
|             ^~~~~~~~
opensnitch.c:372:6: warning: unused variable 'zero_key' [-Wunused-variable]
372 |         u32 zero_key = 0;
```
> Clear out warnings about unused variables

- ui/bin/opensnitch-ui
Fixes error when running `opensnitch-ui` again:
>     if service:
>        ^^^^^^^
> NameError: name 'service' is not defined. Did you mean: 'UIService'?
Fixes: cdf93c72c172 ("ui: fixed delay closing the GUI")
> ui: make sure 'service' variable is set

- ui/opensnitch/dialogs/stats.py
Modify the `_cb_notification_callback` method to properly process notifications that are wrapped in a dictionary to ensure consistent handling regardless of how they're sent from different parts of the codebase.
> ui,stats: handle dict-wrapped notifs in callback

- ebpf_prog/Makefile
This get the build working when building in a chroot or when the running kernel is different from the kernel headers installed.
> Changed how ebpf build find kernel headers from running to installed version.

- daemon/data/rules/000-allow-localhost6.json
- Changed the local host rule from using regexp to network operator
- Updated destination IP check from specific addresses to CIDR notation (127.0.0.0/8)
- Added new rule for IPv6 localhost connections (::1/128)
- Added nolog property to prevent logging of localhost traffic
> refactor: Update localhost rules and add IPv6

- utils/scripts/ipasn_db_sync.sh
This commit adds a new bash script that automates the synchronization of IP-to-ASN and AS names databases for OpenSnitch. The script:
1. Downloads pre-processed ASN data from a GitHub repository
2. Creates backups of existing files before updates
3. Updates ipasn_db.dat.gz and asnames.json files
4. Restores backups if downloads fail
5. Can be run via cron to keep the databases updated
> feat: Add bash script to sync OpenSnitch ASN data

- ebpf_prog/Makefile
This ensure the kernel headers are found during compilation.
> Added ebpf build rule mapping for s390x to s390.

- ebpf_prog/Makefile
This ensure the kernel headers are found during compilation.
> Added ebpf build rule mapping for loongarch64 to loongarch.

- ebpf_prog/Makefile
This ensure the kernel headers are found during compilation.
> Added ebpf build rule mapping for riscv64 to riscv.

- ui/bin/opensnitch-ui
- ui/opensnitch/customwidgets/firewalltableview.py
- ui/opensnitch/customwidgets/updownbtndelegate.py
- ui/opensnitch/dialogs/firewall_rule.py
- ui/opensnitch/firewall/__init__.py
- ui/opensnitch/nodes.py
- ui/opensnitch/notifications.py
> [!WARNING]  
> I didn't actually test the changes, so a test/review would be very much appreciated and required before a potential merge.
My LSP showed some unused imports in the ui source.
For each of the files changed, I searched the corresponding file for the appearance of the seemingly unused import. If it didn't occur anywhere except in the import statement, I removed it.
There were some more occurences where imports currently seem unused but their usage is just commented out at the moment, I didn't remove such.
> ui: remove unused imports

- ui/bin/opensnitch-ui
"dist_path" seems to be a debian thing, in openSUSE for example the path does not exist.
> check whether dist_path exists

- .github/ISSUE_TEMPLATE/bug_report.md
> Simplify uname -a in bug_report.md

- daemon/rule/operator.go
- daemon/rule/operator_test.go
Fixes https://github.com/evilsocket/opensnitch/issues/1318.
The fact that very few relevant things are undocumented makes me do this almost blindly, but from the limited context and knowledge, I do think that empty data field can be present for far more types and operands. But I don't think it makes sense for _all_ types and operands.
> Add ability to match bare IP requests (empty host name)

- ui/i18n/generate_i18n.sh
This should simplify the search for the `lrelease` binary:
`lrelease` - Debian/Ubuntu (?)
`lrelease6` - openSUSE
`lrelease-qt6` - Fedora
In addition, you can specify the path to an `lrelease` binary with `LRELEASE`, e.g.:
`export LRELEASE="/usr/local/bin/my-lrelease-v6"`
> Update generate_i18n.sh - find lrelease
