- opensnitch/app.py
- opensnitch/connection.py
- opensnitch/proc.py
I have a ton of programs written in python and it's not helpful to hear that just python2.7 wants to access the network. I'd like to know which script it was.
> Attempt to resolve script interpreters to the running script

- opensnitch/ui.py
Regarding issue #5 :
Allow/Deny Forever -> Allow/Deny connections that match the current app, host, port and protocol.
Whitelist/Block app -> Permanently allow/block the current app
I also like the Little Snitch option "Until Quit", but UI should be improved first (options and only 2 buttons Allow/Deny for example)..
Tested and working with the current rule.py
> New choices

- README.md
- opensnitch/resources/dialog.ui
- opensnitch/rule.py
- opensnitch/snitch.py
- opensnitch/ui.py
- setup.py
I used PyQt4 in order to support python 2.
You may need to install the package qt4-qtconfig to change theme to GTK+ (since we are running this as root)
> Improving UI (PyQt); implementing "Until Quit" action; App icons;

- bin/opensnitch
> Fixes issue #13 (gtk PyOS_InputHook warning)

- opensnitch/procmon.py
One-line open().write() statements cause file descriptor leaks (and also
look ugly). Instead switch to Go's writefile() style of writing a single
value to a path.
Signed-off-by: Aleksa Sarai <cyphar@cyphar.com>
> procmon: clean up fd leaks

- opensnitch/procmon.py
> Remove useless call to select.select in run. Fixes 100% cpu usage.

- README.md
- bin/opensnitch
- opensnitch/ui.py
> Make sure matplotlib wont load PyQt4, remove PyQt4 compat

- opensnitch/ui.py
> Dont depend on GTK for icon lookups

- opensnitch/app.py
- opensnitch/connection.py
- opensnitch/snitch.py
- setup.py
Also made the following smaller changes:
Don't use homerolled ini-parser
Follow XDG spec for icon locations
Minor PEP8 fixes (app.py is now fully PEP8)
> Use inotify to monitor changes in desktop files

- opensnitch/app.py
> Read .desktop files as utf8

- opensnitch/app.py
> Allow duplicate desktop file entries

- bin/opensnitch
- opensnitch/rule.py
- opensnitch/snitch.py
Not sure if people will want this but I quickly made it so that you can change the location of the database with an argument.
> Added CLI argument for the database path.

- opensnitch/resources/dialog.ui
- opensnitch/ui.py
I hope after this one there will be no more issues with text not resizing it works from small sized window to big size window.
> Fix for the resizing window and text issue

- opensnitch/resources/dialog.ui
This what I can do until I figure out how to trigger automatic resizing. :)
> Minor ui improvements in resizing

- opensnitch/resources/dialog.ui
this is temporary and it will make small windows for small command line and it will gradually open bigger for big command line. I just started messing with this I think if we implement whole app in something like cpp we could use QT and its resize function I just need to find way to use it in python. :)
> resizing should work now

- opensnitch/connection.py
- opensnitch/snitch.py
- opensnitch/ui.py
Not very polished and can't find associated process (psutil does not have icmp support at all) but at least it' better than the current state where no ICMP comes through.
> Add ICMP support

- opensnitch/proc.py
Previously was O(N), now only O(N) in worst case
> Improve code styling and performance in proc.py

- bin/opensnitch
- opensnitch/iptables.py
- opensnitch/snitch.py
- setup.py
Finally an implementation I'm fairly happy with :)
Works fine (even across reboots).
While I'm not happy with adding python-prctl is a dependency (it's not packaged in ubuntu for example) I think this is perfectly fine for now.
We are going to rewrite the daemon later anyway.
> Iptc capsh

- README.md
* Move dependencies from `Install` to `Requirements`
* List dependencies and sort alphabetically
> Add Fedora build dependencies

- README.md
Adding Fedora 26 dependency as mentioned in issue #96.
> Updating README with Fedora 26 dependency

- README.md
Adding Ubuntu dependency as mentioned in issue #95.
> Updating README with Ubuntu dependency

- index.html
> Fix URL for bootstrap template

- ui/requirements.txt
In my environment, I didn't have configparser.  I believe it should be added to requirements.txt.
> Updating requirements.txt with configparser

- README.md
I have added in the README some required libraries to get opensnitchd working.
> added required libraries in README

- README.md
- ui/kcm_opensnitch.desktop
- ui/opensnitch_ui.desktop
- ui/setup.py
I just updated the readme to add autostart instructions... 
i pulled request the rest in other pulls
> adding autostart instructions

- ui/kcm_opensnitch.desktop
- ui/opensnitch_ui.desktop
- ui/setup.py
- Add opensnitch to application menu 
- Add opensnitch to systemsettings
> KDE5 support

- README.md
- make_ads_rules.py
- ui/opensnitch/service.py
> Misc. typos

- daemon/conman/connection.go
- daemon/firewall/rules.go
- daemon/netfilter/queue.go
- daemon/netstat/parse.go
Fixes #206 
https://github.com/jkozera/opensnitch/commit/b5135bd5cdcd5db0d2a0fd161eca6ac2c695df6b + some cleanup from my local upcoming changes for more fixes related to #171.
> IPv6 support

- daemon/rule/operator.go
- daemon/rule/rule.go
- daemon/ui/client.go
Fixes #151 
Not in the way that was planned in #117 but it works. :)
It's https://github.com/jkozera/opensnitch/commit/25e85b05b782ff44de2b4a86d29e8e0d894be98e extracted into a separate branch, to make review independent from the other changes possible.
> Add a 'list' rule type

- README.md
Tested on a freshly installed linux debian distrib
(cf. https://www.debian.org/releases/testing ).
> README.md: add missing steps for TL;DR

- daemon/conman/connection.go
- daemon/core/system.go
- daemon/netfilter/queue.go
- daemon/netlink/socket.go
- daemon/procmon/cache.go
- daemon/procmon/parse.go
- daemon/ui/client.go
- daemon/ui/notifications.go
- ui/opensnitch/customwidgets.py
- ui/opensnitch/desktop_parser.py
- ui/opensnitch/service.py
Found via `codespell v2.1.dev0`  
`codespell -q 3 -L ans`
> Fix random typos

- ui/opensnitch/dialogs/stats.py
A workaround that works on my machine.
> Unminimize maximized windows properly.

- ui/debian/postinst
- ui/debian/templates
I think I really like this method for obtaining extra dependencies. It's very promising and was interesting to see the implementation.
Thanks!
> More precise information regarding pip installations

- ui/i18n/locales/pt_BR/opensnitch-pt_BR.ts
I had to create another branch, do not know what happened that messed things here.
Greetings.
> Update Brazilian Portuguese translation

- daemon/procmon/activepids.go
- daemon/procmon/parse.go
- daemon/procmon/process.go
decreases PID lookup time from ~100usec to ~5usec
> maintain a cache of struct Process for currently active PIDs

- README.md
changed /gustavo-iniguez-goya/ to /evilsocket/
> fixed urls in readme

- wiki/Home.md
Fixes #389.
Please take a look.
> Clarify installation links in home page

- daemon/conman/connection.go
- daemon/main.go
- daemon/procmon/activepids.go
- daemon/procmon/cache.go
- daemon/procmon/ebpf/ebpf.go
- daemon/procmon/monitor/init.go
- daemon/procmon/parse.go
- daemon/procmon/process.go
- daemon/procmon/watcher.go
- daemon/ui/notifications.go
- ebpf_prog/Makefile
- ebpf_prog/README
- ebpf_prog/file.patch
- ebpf_prog/opensnitch.c
before running the branch you have to compile ebpf_prog/opensnitch.c
opensnitch.c is an eBPF program. Compilation requires getting kernel source.
cd opensnitch
wget https://github.com/torvalds/linux/archive/v5.8.tar.gz
tar -xf v5.8.tar.gz
patch linux-5.8/tools/lib/bpf/bpf_helpers.h < ebpf_prog/file.patch
cp ebpf_prog/opensnitch.c ebpf_prog/Makefile linux-5.8/samples/bpf
cd linux-5.8 && yes "" | make oldconfig && make prepare && make headers_install # (1 min)
cd samples/bpf && make
objdump -h opensnitch.o #you should see many section, number 1 should be called kprobe/tcp_v4_connect
llvm-strip -g opensnitch.o #remove debug info
sudo cp opensnitch.o /etc/opensnitchd
cd ../../../daemon
--opensnitchd expects to find opensnitch.o in /etc/opensnitchd/
--start opensnitchd with:
opensnitchd …
> Use ebpf program to find PID of new connections.

- ui/i18n/locales/hu_HU/opensnitch-hu_HU.ts
- ui/i18n/opensnitch_i18n.pro
https://github.com/evilsocket/opensnitch/issues/394#issuecomment-840065445
> Add translation template for hu_HU and sort TRANSLATORS alphabetically

- daemon/go.mod
gobpf was introduced in #397 but not added to go.mod yet
> Add gobpf to go.mod

- ui/Makefile
- ui/opensnitch/config.py
- ui/opensnitch/dialogs/preferences.py
- ui/opensnitch/dialogs/processdetails.py
- ui/opensnitch/dialogs/prompt.py
- ui/opensnitch/dialogs/ruleseditor.py
- ui/opensnitch/dialogs/stats.py
- ui/opensnitch/nodes.py
- ui/opensnitch/service.py
- ui/opensnitch/utils.py
Tested this out, and it should fix current and future module name conflicts for the `opensnitch-ui`
Cheers!
> fixes #439 - module namespace conflict

- ebpf_prog/opensnitch-procs.c
Signed-off-by: Nico Berlee <nico.berlee@on2it.net>
> ebpf: fix compiler issue

- wiki/Installation.md
add command examples for installation / removal using `dnf` (eg: fedora)
> docs: install instructions for dnf distros

- .github/workflows/debian-package.yml
- debian/changelog
- debian/control
- debian/rules
Picked version 1.5.2.1 to be after 1.5.2 and before any new release tagged upstream.
Made sure email in changelog and control matches and fixed some lintian warnings and rebuildability.
> Adjusted some Debian build settings for upload to Debian.

- daemon/main.go
- ui/bin/opensnitch-ui
Based on git history with no lower threshold on contributions, so any contributors get a copyright claim in the code.
> Added copyright and license header to daemon/main.go and ui/bin/opensnitch-ui.

- .github/workflows/build_ebpf_modules.yml
- .github/workflows/go.yml
Bumps actions to the latest in the workflow folder
> Bump workflow actions

- daemon/opensnitchd.service
replace that "https://github.com/gustavo-iniguez-goya/opensnitch/wiki" link 
to "https://github.com/evilsocket/opensnitch/wiki" link
> Replace docs link in opensnitchd.service

- ui/resources/io.github.evilsocket.opensnitch.appdata.xml
Made sure the base name used matches the svg and png icons provided.
> Corrected appstream icon name.

- wiki/Installation.md
https://github.com/gustavo-iniguez-goya/opensnitch/releases --> https://github.com/evilsocket/opensnitch/releases
https://github.com/gustavo-iniguez-goya/opensnitch/wiki/Known-problems --> https://github.com/evilsocket/opensnitch/wiki/Known-problems
> Updated links pointing to the old fork - wiki installation page

- ui/requirements.txt
Bump this component to the latest released version
> ui: bump unicode_slugify to 0.1.5

- daemon/opensnitchd-dinit
> Dinit service file

- ui/i18n/locales/zh_TW/opensnitch-zh_TW.ts
- ui/i18n/opensnitch_i18n.pro
It's not perfect, but will improve it later!
> Add basic Traditional Chinese locale

- wiki/Configurations.md
Updated the Single UI with many computers section. Clarified information regarding commands for client and GUI hosts. Added subsection on how to make client configurations persistent for the single UI setup.
> Update Configurations.md Remote Client Configuration

- ui/i18n/locales/id_ID/opensnitch-id_ID.ts
- ui/i18n/opensnitch_i18n.pro
- add Indonesian translation
- sort translation files in opensnitch_i18n.pro
> Add Indonesian translation

- README.md
Fix discord link being accidentally nested, it still worked before though.
> Update README.md - Fix Discord link nesting

- daemon/core/version.go
Synchronize version with latest release & tag.
> chore: update version to 1.6.8

- ui/i18n/locales/ru_RU/opensnitch-ru_RU.ts
@gustavo-iniguez-goya,
Hello!
I have updated the Russian localization, and it is now 100% complete. 
Thank you for your review and for creating such amazing software!
BR
> Update i18n ru_RU

- utils/scripts/ipasn_db_update.sh
This script uses the `pyasn` project to download and update ipasn and asnames data.
> feat: Add script to automatically update ipasn and asnames databases
